//$file${.::../Inc::knob.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: MotionController.qm
// File:  ${.::../Inc::knob.hpp}
//
// This code has been generated by QM 7.0.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::../Inc::knob.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef KNOB_H
#define KNOB_H

#include <cstdint>

#include "qpcpp.hpp"             // QP/C++ real-time embedded framework

//$declare${AOs::Knob} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Knob} ...............................................................
class Knob : public QP::QActive {
public:
    static Knob inst;
    std::int8_t m_position;

private:
    QP::QTimeEvt m_timeEvt;

public:
    std::uint16_t m_notifyCount= 0;
    std::int8_t m_lastPosition;
    QP::QActive * m_AO_Client;

private:
    void CreatePeriodicTimer(uint32_t time);
    void SendKnobEvent(uint16_t position);
    std::uint8_t CheckKnobChanged();

public:
    Knob();

private:
    void CreateOneShotTimer(uint32_t time);
    void StopTimer();
    void PublishPositionEvent();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(running);
    Q_STATE_DECL(idle);
    Q_STATE_DECL(updatePosition);
}; // class Knob

} // namespace APP
//$enddecl${AOs::Knob} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
