//$file${.::../Inc::motor.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: MotionController.qm
// File:  ${.::../Inc::motor.hpp}
//
// This code has been generated by QM 7.0.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::../Inc::motor.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef MOTOR_H
#define MOTOR_H

#include <cstdint>

#include "qpcpp.hpp"             // QP/C++ real-time embedded framework

//$declare${AOs::Motor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Motor} ..............................................................
class Motor : public QP::QActive {
private:
    QP::QTimeEvt m_timeEvt;

public:
    static Motor inst;
    std::int16_t m_position;

private:
    std::int8_t m_moving;
    std::int16_t m_positionRequest;

public:
    std::int16_t m_increment;
    std::uint32_t m_stepDelay;
    std::uint8_t m_atLimitSwitch;
    std::uint8_t m_findingLimit;
    std::uint8_t m_error;
    QP::QActive * m_AO_Client;

private:
    std::int8_t MotionDone();
    std::int16_t MoveMotor();
    void CreateOneShotTimer(uint32_t time);
    void SendMotionDoneEvent();
    void SendMotionErrorEvent();

public:
    Motor();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(MotionReady);
    Q_STATE_DECL(Moving);
    Q_STATE_DECL(Stopped);
}; // class Motor

} // namespace APP
//$enddecl${AOs::Motor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
